//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITSupportTicket
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblStaffTicket
    {
        public int StaffTicketId { get; set; }
        public Nullable<int> TicketId { get; set; }
        public string StaffEmail { get; set; }
        public string UserEmail { get; set; }
        public string Subject { get; set; }
        public string Attachment { get; set; }
        public string Message { get; set; }
    
        public virtual tblTicket tblTicket { get; set; }
    }
}
